name: Ubuntu 20.04 x86_64 Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Workspace directories creation
      run: mkdir lib && mkdir include && mkdir src
    - uses: actions/checkout@v2
      with:
        repository: rustyducks/navigation
        path: src/navigation
    - uses: actions/checkout@v2
      with:
          repository: rustyducks/geometry_tools
          path: src/geometry_tools
    - name: Install dependencies
      run: sudo add-apt-repository ppa:paparazzi-uav/ppa && sudo apt-get update && sudo apt-get install -y ivy-c-dev libeigen3-dev
    - name: Build directories creation
      run:  mkdir src/geometry_tools/build && mkdir src/navigation/build
    - name: Geometry Tools build and install
      working-directory: src/geometry_tools/build
      run: cmake -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE .. && make -j4 && make install
    - name: Cmake configure
      working-directory: src/navigation/build
      run: cmake -DENABLE_TESTS=ON -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE ..
    - name: make
      working-directory: src/navigation/build
      run: make -j4
    - name: test
      working-directory: src/navigation/build
      run: ctest -V
